scrape_configs:
  - job_name: reth
    metrics_path: "/"
    scrape_interval: 5s
    static_configs:
      - targets: ['reth:9001']
  - job_name: lighthouse
    metrics_path: "/metrics"
    scrape_interval: 5s
    static_configs:
      - targets: [ 'lighthouse:5054' ]
  - job_name: ethereum-metrics-exporter
    metrics_path: "/metrics"
    scrape_interval: 5s
    static_configs:
      - targets: ['metrics-exporter:9091']